function printReturnPredictionSection(fid, Results)
% PURPOSE: This function is part of the protocol of tests for proposed new
% cross-sectional anomaly signals established in Novy-Marx and Velikov
% (2023). It prints the the Return Predictability section in the latex file. 
%------------------------------------------------------------------------------------------
% USAGE:   
% printReturnPredictionSection(fid, Results)
%------------------------------------------------------------------------------------------
% Required Inputs:
%        - fid - file ID for writing
%        - Results - structure with results that are used to print the .tex
%                    latex file and .pdf figures
%------------------------------------------------------------------------------------------
% Output:
%        - N/A
%------------------------------------------------------------------------------------------
% Examples:
%
% printReturnPredictionSection(fid, Results)
%------------------------------------------------------------------------------------------
% Dependencies:
%       N/A
%------------------------------------------------------------------------------------------
% Copyright (c) 2023 All rights reserved. 
%       Robert Novy-Marx <robert.novy-marx@simon.rochester.edu>
%       Mihail Velikov <velikov@psu.edu>
% 
%  References
%  1. Novy-Marx, R. and M. Velikov, 2023, Assaying anomalies, Working paper.

% Load the dates vector
load dates

% Determine the sample
s = find(dates==Results.Text.timePeriod(1));
e = find(dates==Results.Text.timePeriod(2));

% Discuss Table 1, Panel A
signalChar = Results.Text.signalChar;
averageRet = sprintf('%2.2f',Results.Tab_BasicSort.PanelA.a(1,end));
averageTRet = sprintf('%2.2f',Results.Tab_BasicSort.PanelA.tA(1,end));
alphas = Results.Tab_BasicSort.PanelA.a(2:end, end);
alphaMin = sprintf('%2.2f', min(alphas));
alphaMax = sprintf('%2.2f', max(alphas));
talphaMin = sprintf('%2.2f', min(Results.Tab_BasicSort.PanelA.tA(2:end, end)));
alphaMinInd = find(alphas <= min(alphas), 1, 'first');
alphaMinFactorModel = char(extractBetween(Results.Tab_BasicSort.PanelA.h(alphaMinInd+1),'{','}'));

fprintf(fid, ['\\section{Does ', signalChar, ' predict returns?} \n']);
fprintf(fid, ['\\label{sec:returnPrediction}' '\n\n\n']);

section_3_text = [ ...
    'Table~\\ref{tab:tsRegs} reports the performance of portfolios constructed using a value-weighted, quintile sort on  ', ...
    signalChar, ' using NYSE breaks. The first two lines of Panel A report monthly average excess returns ', ...        
    'for each of the five portfolios and for the long/short portfolio that buys the high ', signalChar, ...
    ' portfolio and sells the low ', signalChar, ' portfolio. The rest of Panel A reports the portfolios'' ', ...
    'monthly abnormal returns relative to the five most common factor models: the CAPM, the \\citet{FamaFrench1993} ' , ...
    'three-factor model (FF3) and its variation that adds momentum (FF4), the \\citet{FamaFrench2015} ', ...
    'five-factor model (FF5), and its variation that adds momentum factor used in \\citet{FamaFrench2018} (FF6). ', ...
    'The table shows that the long/short ', signalChar, ...
    ' strategy earns an average return of ', averageRet, '\\%% per month with a t-statistic of ', averageTRet, ...
    '. The annualized Sharpe ratio of the strategy is ', Results.Text.sharpeChar, '. ', ...
    'The alphas range from ', alphaMin, '\\%% to ', alphaMax, '\\%% per month and have t-statistics exceeding ', ...
    talphaMin, ' everywhere. The lowest alpha is with respect to the ', alphaMinFactorModel, ' factor model.' '\n\n\n'];
fprintf(fid, section_3_text);  

% Discuss Table 1, Panels B and C    
tbetas = Results.Tab_BasicSort.PanelB.tA(:, end);
maxTBetaInd = find(abs(tbetas) >= max(abs(tbetas)), 1, 'first');
maxBeta = sprintf('%2.2f', Results.Tab_BasicSort.PanelB.a(maxTBetaInd, end));
maxTBeta = sprintf('%2.2f', tbetas(maxTBetaInd));
maxTBetaLabel = char(extractBetween(Results.Tab_BasicSort.PanelB.h(maxTBetaInd), '\text{','}'));

nStocks = Results.Tab_BasicSort.PanelC.a(1,1:end);
minNStocksInd = find(nStocks <= min(nStocks), 1, 'first');
minNStocks = addComma(nStocks(minNStocksInd));

mCaps = Results.Tab_BasicSort.PanelC.a(2,1:end);
minMCapsInd = find(mCaps <= min(mCaps), 1, 'first');
minMCaps = addComma(mCaps(minMCapsInd));
        
section_3_text = [ ...
    'Panel B reports the six portfolios'' loadings on the factors in the \\citet{FamaFrench2018} six-factor model.  ', ...
    'The long/short strategy''s most significant loading is ', maxBeta, ', with a t-statistic of ', maxTBeta, ...
    ' on the ', maxTBetaLabel, ' factor. Panel C reports the average number of ', ...
    'stocks in each portfolio, as well as the average market capitalization (in \\$ millions) ', ...
    'of the stocks they hold. In an average month, ', ...
    'the five portfolios have at least ', minNStocks, ' stocks and an average market capitalization ', ...
    'of at least \\$', minMCaps, ' million.' '\n\n\n'];
fprintf(fid, section_3_text);  

% Discuss Table 2, Panel A    
rets = Results.Tab_RobustSort.PanelA.a(:,1);
h = Results.Tab_RobustSort.PanelA.h;

minRetInd = find(rets <= min(rets), 1, 'first');
minRet = sprintf('%2.0f', 100*rets(minRetInd));
minTRet = sprintf('%2.2f', Results.Tab_RobustSort.PanelA.tA(minRetInd, 1));
minRetLabel = lower(split(h(minRetInd), ' & ')');
if strcmp(minRetLabel(3), 'vw')
    minRetLabel(3) = {'value-weighted'};
else
    minRetLabel(3) = {'equal-weighted'};
end
if strcmp(minRetLabel(2), 'nyse')
    minRetLabel(2) = {'NYSE'};
end

talphas = Results.Tab_RobustSort.PanelA.tA(:,2:end);
numTAlphaGT2 = num2words(sum(sum(talphas>2)));
numTAlphaGT3 = num2words(sum(sum(talphas>3)));


section_3_text = [ ...
    'Table~\\ref{tab:robustnessToSorting} reports robustness results for alternative sorting methodologies, ', ...
    'and accounting for transaction costs. These results are important, because many anomalies are far ', ...
    'stronger among small cap stocks, but these small stocks are more expensive to trade. ', ...
    'Construction methods, or even signal-size correlations, that over-weight small stocks can ', ...
    'yield stronger paper performance without improving an investor''s achievable investment opportunity set. ', ...
    'Panel A reports gross returns and alphas for the long/short strategies made using various different protfolio ', ...
    'constructions. The first row ', ...
    'reports the average returns and the alphas for the long/short strategy from Table~\\ref{tab:tsRegs}, which is ', ...
    'constructed from a quintile sort using NYSE breakpoints and value-weighted portfolios. The rest of the panel ',...
    'shows the equal-weighted returns to this same strategy, and the value-weighted performance of strategies ', ...
    'constructed from quintile sorts using name breaks (approximately equal number of firms in each portfolio) and ', ...
    'market capitalization breaks (approximately equal total market capitalization in each portfolio), and using ', ...
    'NYSE deciles. The average return is lowest for the ', char(minRetLabel(1)), ' sort using ', char(minRetLabel(2)), ...
    ' breakpoints and ', char(minRetLabel(3)), ' portfolios, and equals ', minRet, ' bps/month with a t-statistics ', ...
    'of ', minTRet, '. Out of the twenty-five alphas reported in Panel A, the t-statistics for ', numTAlphaGT2, ...
    ' exceed two, and for ' numTAlphaGT3, ' exceed three.' '\n\n\n'];
fprintf(fid, section_3_text);  

% Discuss Table 2, Panel B
rets = Results.Tab_RobustSort.PanelB.a(:,1);
h = Results.Tab_RobustSort.PanelB.h;

minRetInd = find(rets <= min(rets), 1, 'first');
minRet = sprintf('%2.0f', 100*rets(minRetInd));
minTRet = sprintf('%2.2f', Results.Tab_RobustSort.PanelB.tA(minRetInd, 1));
minRetLabel = lower(split(h(minRetInd), ' & ')');    
if strcmp(minRetLabel(3), 'vw')
    minRetLabel(3) = {'value-weighted'};
else
    minRetLabel(3) = {'equal-weighted'};
end
if strcmp(minRetLabel(2), 'nyse')
    minRetLabel(2) = {'NYSE'};
end
maxRetInd = find(rets>=max(rets), 1, 'first');
maxRet = sprintf('%2.0f', 100*rets(maxRetInd));
numAlphasFin = num2words(sum(sum(isfinite(Results.Tab_RobustSort.PanelB.a(:,2:end)))));
numAlphasSig = num2words(sum(sum(Results.Tab_RobustSort.PanelB.tA(:,2:end)>=1.96)));


if strcmp(Results.Text.tcostsType, 'gibbs')
    tcostsDescription = ['The transaction costs are calculated as the ', ...
                         'Gibbs effective bid-ask ', ...
                         'half-spread measure from \\citet{Hasbrouck2009}. '];
elseif strcmp(Results.Text.tcostsType, 'lf_combo')
    tcostsDescription = ['The transaction costs are calculated as the ', ...
                         'low-frequency composite effective bid-ask ', ...
                         'half-spread measure from \\citet{ChenVelikov2022}. '];
elseif strcmp(Results.Text.tcostsType, 'full')
     tcostsDescription = ['The transaction costs are calculated as the ', ...
                         'high-frequency composite effective bid-ask ', ...
                         'half-spread measure from \\citet{ChenVelikov2022}. '];
   
end

section_3_text = [ ...
    'Panel B reports for these same strategies the average monthly ', ...
    'net returns and the generalized net alphas of \\citet{Novy-MarxVelikov2016}. ', ...
    'These generalized alphas measure the extent to which a test asset improves the ex-post mean-variance ', ...
    'efficient portfolio, accounting for the costs of trading both the asset and the explanatory factors. ', ...
    tcostsDescription, ...
    'The net average returns reported in the first column range between ', minRet '-', maxRet, ...
    'bps/month. The lowest return, (', minRet, ' bps/month), is achieved from the ', char(minRetLabel(1)), ...
    ' sort using ', char(minRetLabel(2)), ' breakpoints and ', char(minRetLabel(3)), ' portfolios, and has an ', ...
    'associated t-statistic of ', minTRet, '. Out of the twenty-five construction-methodology-factor-model pairs ', ...
    'reported in Panel B, the ', signalChar, ' trading strategy improves the achievable mean-variance efficient ', ...
    'frontier spanned by the factor models in ', ...
    numAlphasFin, ' cases, and significantly expands the achievable frontier in ', ...
    numAlphasSig, ' cases.' '\n\n\n'];
fprintf(fid, section_3_text);  


% Discuss Table 3, Panel A     
largeCapRet = sprintf('%2.0f', 100*Results.Tab_CondSizeSort.PanelA.a(end, 7));
largeCapTRet = sprintf('%2.2f', Results.Tab_CondSizeSort.PanelA.tA(end, 7));
alphas = Results.Tab_CondSizeSort.PanelA.a(end, 8:end);
tAlphas = Results.Tab_CondSizeSort.PanelA.tA(end, 8:end);
indMin = find(alphas == min(alphas));
alphaMin = sprintf('%2.0f', 100*alphas(indMin));
tAlphaMin = sprintf('%2.2f', tAlphas(indMin));

indMax = find(alphas == max(alphas));
alphaMax = sprintf('%2.0f', 100*alphas(indMax));
tAlphaMax = sprintf('%2.2f', tAlphas(indMax));

section_3_text = [ ...
    'Table~\\ref{tab:doubleSortSize} provides direct tests for the role size plays in the ', ...
    signalChar, ' strategy performance. Panel A reports the average returns for the ', ...
    'twenty-five portfolios constructed from a conditional double sort on size and ', signalChar, ', ', ...
    'as well as average returns and alphas for long/short trading ', signalChar, ' strategies within ', ...
    'each size quintile. Panel B reports the average number of stocks and the average firm size ', ...
    'for the twenty-five portfolios. Among the largest stocks (those with market capitalization greater than the 80$^\\text{th}$ ', ...
    'NYSE percentile), the ', signalChar, ' strategy achieves an average return of ', ...
    largeCapRet, ' bps/month with a t-statistic of ', largeCapTRet, '. Among these large cap stocks, the alphas for the ', ...
    signalChar, ' strategy relative to the five most common factor models ', ...
    'range from ', alphaMin, ' to ', alphaMax, ' bps/month with t-statistics between ', ...
    tAlphaMin, ' and ', tAlphaMax, '.' '\n\n\n'];
fprintf(fid, section_3_text);  

