function printBibliographyFile(filePath)
% PURPOSE: This function is part of the protocol of tests for proposed new
% cross-sectional anomaly signals established in Novy-Marx and Velikov
% (2023). It prints the bibliography. 
%------------------------------------------------------------------------------------------
% USAGE:   
% printBibliographyFile(filePath)
%------------------------------------------------------------------------------------------
% Required Inputs:
%        - filePath - the file path where the bibliography file is to be
%                     stored
%------------------------------------------------------------------------------------------
% Output:
%        - N/A
%------------------------------------------------------------------------------------------
% Examples:
%
% printBibliographyFile(filePath)
%------------------------------------------------------------------------------------------
% Dependencies:
%       N/A
%------------------------------------------------------------------------------------------
% Copyright (c) 2023 All rights reserved. 
%       Robert Novy-Marx <robert.novy-marx@simon.rochester.edu>
%       Mihail Velikov <velikov@psu.edu>
% 
%  References
%  1. Novy-Marx, R. and M. Velikov, 2023, Assaying anomalies, Working paper.


% Make the bibliography file
% choose the Latex file name
fileName = [filePath, 'newSignalTestBib.bib'];
delete(fileName);

% Document header
fid = fopen(fileName, 'at');
fprintf(fid, ['@article{FamaMacBeth1973,' '\n' ...
                        'title={Risk, return, and equilibrium: empirical tests},' '\n' ...
                        'journal ={Journal of Political Economy},' '\n' ...
                        'volume=81,' '\n' ...
                        'number =3,' '\n' ...
                        'pages = {607-636},' '\n' ...
                        'year =1973,' '\n' ...
                        'author ={Eugene F. Fama and James D. MacBeth}}' '\n']);
fprintf(fid, ['@article{FamaFrench1993,' '\n' ...
                        'title={Common risk factors in the returns on stocks and bonds},' '\n' ...
                        'journal ={Journal of Financial Economics},' '\n' ...
                        'volume=33,' '\n' ...
                        'number =1,' '\n' ...
                        'pages = {3-56},' '\n' ...
                        'year =1993,' '\n' ...
                        'author ={Eugene F. Fama and Kenneth R. French}}' '\n']);
fprintf(fid, ['@article{Carhart1997,' '\n' ...
                        'title={On Persistence in Mutual Fund Performance},' '\n' ...
                        'journal ={Journal of Finance},' '\n' ...
                        'volume=52,' '\n' ...
                        'pages = {57-82},' '\n' ...
                        'year =1997,' '\n' ...
                        'author ={Carhart, M. M.}}' '\n']);
fprintf(fid, ['@article{FamaFrench2015,' '\n' ...
                        'author = {Fama,Eugene F. and French,Kenneth R.},' '\n' ...
                        'year={2015},' '\n' ...
                        'title={A five-factor asset pricing model},' '\n' ...
                        'journal={Journal of Financial Economics},' '\n' ...
                        'volume={116},' '\n' ...
                        'number={1},' '\n' ...
                        'pages={1-22}}' '\n']);
fprintf(fid, ['@article{Novy-MarxVelikov2016,' '\n' ...
                        'author = {Novy-Marx, Robert and Mihail Velikov},' '\n' ...
                        'year={2016},' '\n' ...
                        'title={A taxonomy of anomalies and their trading costs},' '\n' ...
                        'journal={Review of Financial Studies},' '\n' ...
                        'volume={29},' '\n' ...
                        'number={1},' '\n' ...
                        'pages={104-147}}' '\n']);                    
fprintf(fid, ['@article{FamaFrench2018,' '\n' ...
                        'author = {Fama,Eugene F. and French,Kenneth R.},' '\n' ...
                        'year={2018},' '\n' ...
                        'title={Choosing factors},' '\n' ...
                        'journal={Journal of Financial Economics},' '\n' ...
                        'volume={128},' '\n' ...
                        'number={2},' '\n' ...
                        'pages={234--252}}' '\n']);
fprintf(fid, ['@article{Novy-MarxVelikov2023,' '\n' ...
                        'author = {Novy-Marx, Robert and Mihail Velikov},' '\n' ...
                        'year={2023},' '\n' ...
                        'title={Assaying anomalies},' '\n' ...
                        'journal={Working paper}}' '\n']); 
fprintf(fid, ['@article{DetzelNovy-MarxVelikov2022,' '\n' ...
                        'author = {Detzel, Andrew and Novy-Marx, Robert and Mihail Velikov},' '\n' ...
                        'year={2022},' '\n' ...
                        'title={Model comparison with transaction costs},' '\n' ...
                        'journal={Journal of Finance, Forthcoming}}' '\n']); 
fprintf(fid, ['@article{LightMaslovRytchkov2017,' '\n' ...
                        'author = {Light, Nathaniel and Maslov, Denys and Oleg Rytchkov},' '\n' ...
                        'year={2017},' '\n' ...
                        'title={Aggregation of Information  about the Cross Section of Stock Returns: A Latent  Variable Approach},' '\n' ...
                        'journal={Review of Financial Studies},' '\n' ...
                        'volume={30},' '\n' ...
                        'pages={1339--1381}}' '\n']);                        
fprintf(fid, ['@article{ChenVelikov2022,' '\n' ...
                        'author = {Chen, Andrew and Mihail Velikov},' '\n' ...
                        'year={2022},' '\n' ...
                        'title={Zeroing in on the Expected Returns of Anomalies},' '\n' ...
                        'journal={Journal of Financial and Quantitative Analysis},' '\n' ...
                        'volume={Forthcoming}}' '\n']); 
fprintf(fid, ['@article{Lewellen2015,' '\n' ...
                        'title={The cross-section of expected returns},' '\n' ...
                        'journal ={Critical Finance Review},' '\n' ...
                        'volume=4,' '\n' ...
                        'number =1,' '\n' ...
                        'pages = {1-44},' '\n' ...
                        'year =2015,' '\n' ...
                        'author ={Jonathan Lewellen}}' '\n']);    
fprintf(fid, ['@article{HaugenBaker1996,' '\n' ...
                        'title={Commonality in the determinants of expected stock returns},' '\n' ...
                        'journal ={Journal of Financial Economics},' '\n' ...
                        'volume=41,' '\n' ...
                        'number =3,' '\n' ...
                        'pages = {401-439},' '\n' ...
                        'year =1996,' '\n' ...
                        'author ={Robert A. Haugen and Nardin L. Baker}}' '\n']);    
fprintf(fid, ['@article{KellyPruittSu2019,' '\n' ...
                        'title={Characteristics are covariances: A unified model of risk and return},' '\n' ...
                        'journal ={Journal of Financial Economics},' '\n' ...
                        'volume=134,' '\n' ...
                        'number =3,' '\n' ...
                        'pages = {501-524},' '\n' ...
                        'year =2019,' '\n' ...
                        'author ={Bryan T. Kelly and Seth Pruitt and Yinan Su}}' '\n']);    
fprintf(fid, ['@article{ChenZimmermann2022,' '\n' ...
                        'title={Open Source Cross-Sectional Asset Pricing},' '\n' ...
                        'journal ={Critical Finance Review},' '\n' ...
                        'volume=27,' '\n' ...
                        'number =2,' '\n' ...
                        'pages = {207--264},' '\n' ...
                        'year =2022,' '\n' ...
                        'author ={Andrew Y. Chen and Tom Zimmermann}}' '\n']);    

fclose(fid);
