function printCloseAnomsSection(fid, Results)
% PURPOSE: This function is part of the protocol of tests for proposed new
% cross-sectional anomaly signals established in Novy-Marx and Velikov
% (2023). It prints the the Close Anomalies section in the latex file. 
%------------------------------------------------------------------------------------------
% USAGE:   
% printCloseAnomsSection(fid, Results)
%------------------------------------------------------------------------------------------
% Required Inputs:
%        - fid - file ID for writing
%        - Results - structure with results that are used to print the .tex
%                    latex file and .pdf figures
%------------------------------------------------------------------------------------------
% Output:
%        - N/A
%------------------------------------------------------------------------------------------
% Examples:
%
% printCloseAnomsSection(fid, Results)
%------------------------------------------------------------------------------------------
% Dependencies:
%       N/A
%------------------------------------------------------------------------------------------
% Copyright (c) 2023 All rights reserved. 
%       Robert Novy-Marx <robert.novy-marx@simon.rochester.edu>
%       Mihail Velikov <velikov@psu.edu>
% 
%  References
%  1. Novy-Marx, R. and M. Velikov, 2023, Assaying anomalies, Working paper. 

% Store a few results
nAnoms = Results.Text.nAnoms;
signalChar = Results.Text.signalChar;

% Add the section title
fprintf(fid, ['\\section{Does ', signalChar, ' add relative to related anomalies?} \n']);
fprintf(fid, ['\\label{sec:closeAnoms}' '\n\n\n']);


% Intro paragraph to Section 5
section_5_text = [ ...
    'With so many anomalies, it is possible that any proposed, new cross-sectional ', ...
    'predictor is just capturing some combination of known predictors. It is consequently ', ...
    'natural to investigate to what extent the proposed predictor adds additional ', ... 
    'predictive power beyond the most closely related anomalies. ' '\n'];
fprintf(fid, section_5_text);  


% Describe Figures 5 and 6
section_5_text = [ ...
    'Closely related anomalies are more likely to be formed on the basis of signals ', ...
    'with higher absolute correlations. Figure~\\ref{fig:distributionCorrelations} plots ', ...
    'a name histogram of the correlations of ', signalChar, ' with the ', nAnoms, ' anomaly signals. ', ...
    'Figure~\\ref{fig:hierarchicalClusterPlot} also shows an agglomerative hierarchical cluster ', ...
    'plot using Ward''s minimum method and a maximum of 10 clusters.  ' '\n\n\n'];
fprintf(fid, section_5_text);          


% Describe Figure 7
section_5_text = [ ...
          'A closely related anomaly is also more likely to price ', signalChar, ' ', ...
          'or at least to weaken the power ', signalChar, ' has predicting the cross-section of returns. ', ...
          'Figure~\\ref{fig:conditionalStrategies} plots histograms of t-statistics for predictability tests of ', signalChar, ' ', ...
          'conditioning on each of the ', nAnoms, ' anomaly signals one at a time. ', ...
          'Panel A reports t-statistics on $\\beta_{', signalChar, '}$', ...
          ' from Fama-MacBeth regressions of the form $r_{i,t} = \\alpha + \\beta_{', signalChar, '}', ...
          signalChar, '_{i,t} + \\beta_X X_{i,t}+\\epsilon_{i,t}$, ', ...
          'where $X$ stands for one of the ', nAnoms, ' anomaly signals at a time. ', ...
          'Panel B plots t-statistics on $\\alpha$ from spanning tests of the form: ', ...
          '$r_{',signalChar, ', t} = \\alpha + \\beta r_{X, t}+\\epsilon_t$, ', ...
          'where $r_{X,t}$ stands for the returns to one of the ', nAnoms, ' anomaly trading strategies at a time. ', ...                  
          'The strategies employed in the spanning tests are constructed using quintile sorts, value-weighting, and NYSE breakpoints. ', ...
          'Panel C plots t-statistics on the average returns to strategies constructed by conditional double sorts. ', ...
          'In each month, we sort stocks into quintiles based one of the ', nAnoms, ...
          ' anomaly signals. Then, within each quintile, ', ...
          'we sort stocks into quintiles based on ', signalChar, '. Stocks are finally grouped into ', ...
          'five ', signalChar, ' portfolios by combining stocks within each anomaly sorting portfolio. ', ...
          'The panel plots the t-statistics on the average returns of these conditional double-sorted ', signalChar, ...
          ' trading strategies conditioned on each of the ', nAnoms, ' anomalies.' '\n\n\n'];
fprintf(fid, section_5_text);  

% Discuss Table 4
minIndTStatInd = find(Results.Tab_CloseFMB.tA(2, 1:end-1) == min(Results.Tab_CloseFMB.tA(2,1:end-1)));
minIndTstat = sprintf('%.2f', Results.Tab_CloseFMB.tA(2, minIndTStatInd));
minIndTStatLabel = char(Results.Text.closeAnomLabels(minIndTStatInd));
allTstat = sprintf('%.2f', Results.Tab_CloseFMB.tA(2, end));
nCloseAnomsChar = num2words(Results.Text.nCloseAnoms);

section_5_text = [ ...
    'Table~\\ref{tab:closeAnomFMB} reports Fama-MacBeth cross-sectional regressions ', ...
    'of returns on ', signalChar, ' and the ', nCloseAnomsChar, ' anomalies most closely-related to it. ', ...
    'The ', nCloseAnomsChar, ' most-closely related anomalies are picked as those with the highest combined rank ', ...
    'where the ranks are based on the absolute value of the Spearman correlations in Panel B ', ...
    'of Figure~\\ref{fig:distributionCorrelations} '...
    'and the $R^{2}$ from the spanning tests in Figure~\\ref{fig:conditionalStrategies}, Panel B. ', ...
    'Controlling for each of these signals at a time, the t-statistics on the ', signalChar, ' signal ', ...
    'in these Fama-MacBeth regressions exceed ', minIndTstat, ', with the minimum t-statistic occurring when ', ...
    'controlling for ', minIndTStatLabel, '. Controlling ', ...
    'for all ', nCloseAnomsChar, ' closely related anomalies, the t-statistic on ', signalChar, ...
    ' is ', allTstat, '.' '\n\n\n'];
fprintf(fid, section_5_text);  

% Discuss Table 5
minAlpha = sprintf('%2.0f', 100*min(Results.Tab_CloseSpan.a(1,1:end-1)));
maxAlpha = sprintf('%2.0f', 100*max(Results.Tab_CloseSpan.a(1,1:end-1)));

minAlphaTStatInd = find(Results.Tab_CloseSpan.tA(1, 1:end-1) == min(Results.Tab_CloseSpan.tA(1,1:end-1)));
minAlphaTstat = sprintf('%.2f', Results.Tab_CloseSpan.tA(1, minAlphaTStatInd));
minAlphaTStatLabel = char(Results.Text.closeAnomLabels(minIndTStatInd));

allAlpha = sprintf('%2.0f', 100*Results.Tab_CloseSpan.a(1, end));
allTstat = sprintf('%.2f', Results.Tab_CloseSpan.tA(1, end));

section_5_text = [ ...
    'Similarly, Table~\\ref{tab:closeAnomSpan} reports results from spanning tests ', ...
    'that regress returns to the ', signalChar, ' strategy onto the returns of ', ...
    'the ', nCloseAnomsChar, ' most closely-related anomalies and ', ...
    'the six Fama-French factors. Controlling for the ', nCloseAnomsChar, ' most-closely related ', ...
    'anomalies individually, the ', signalChar, ' strategy earns alphas that range ', ...
    'from ', minAlpha, '-', maxAlpha, 'bps/month. The minimum t-statistic ', ...
    'on these alphas controlling for one anomaly at a time is ', minAlphaTstat, ', which ', ...
    'is achieved when controlling for ', minAlphaTStatLabel, '. Controlling for ', ...
    'all ', nCloseAnomsChar, ' closely-related anomalies and the six Fama-French factors simultaneously, the ', signalChar, ...
    ' trading strategy achieves an alpha of ', allAlpha, 'bps/month with a ', ...
    't-statistic of ', allTstat, '.' '\n\n\n'];
fprintf(fid, section_5_text);  

